# Generated by Django 2.1.8 on 2019-06-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='scheduling_time',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
