# Generated by Django 2.1.8 on 2019-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_auto_20190615_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='scheduling_time',
            field=models.CharField(max_length=20),
        ),
    ]
