# Generated by Django 2.1.8 on 2019-06-15 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_event_is_dealing'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_change_user',
            field=models.ForeignKey(db_column='change_user_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='change_user', to='port.User'),
            preserve_default=False,
        ),
    ]
