# Generated by Django 2.1.8 on 2019-06-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0006_leave_leave_change_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together={('leave_user', 'leave_change_user')},
        ),
    ]
