# Generated by Django 2.1.8 on 2019-06-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_auto_20190615_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_main_deal',
            field=models.ForeignKey(db_column='main_deal_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_deal', to='port.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_solve',
            field=models.ForeignKey(db_column='solver_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solver_user', to='port.User'),
        ),
    ]
